version: '2'

services:
  budgetmetal_admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    image: budgetmetaladmin
    build:
      context: .
      dockerfile: BudgetMetal_Admin/Dockerfile
      network: dockernet
    ports:
      - 9908:80

  com.budgetmetal.services.gallery:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    image: combudgetmetalservicesgallery
    build:
      context: .
      dockerfile: Com.BudgetMetal.Services.Gallery/Dockerfile
      network: dockernet
    ports:
    - 9909:80

networks:
    dockernet:
        external: true

