version: '2'

services:
  budgetmetal_admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    image: budgetmetaladmin
    #network_mode: bridge
    #networks:
            #- dockernet
    build:
      context: .
      dockerfile: BudgetMetal_Admin/Dockerfile
    ports:
      - "9908:80"

  com.budgetmetal.services.gallery:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    image: combudgetmetalservicesgallery
    #network_mode: bridge
    #networks:
            #- dockernet
    build:
      context: .
      dockerfile: Com.BudgetMetal.Services.Gallery/Dockerfile
    ports:
      - "9909:80"

networks:
    dockernet:
        external: true

