version: '2'

services:
  budgetmetal_admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: budgetmetaladmin
    network_mode: host
    #networks:
      #- dockernet
    build:
      context: .
      dockerfile: BudgetMetal_Admin/Dockerfile
    ports:
      - "9908:80"

  com.budgetmetal.services.galleryapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: combudgetmetalservicesgalleryapi
    network_mode: host
    #networks:
      #- dockernet
    build:
      context: .
      dockerfile: Com.BudgetMetal.Services.GalleryAPI/Dockerfile
    ports:
      - "9909:80"

  com.budgetmetal.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: combudgetmetalapp
    network_mode: host
    #networks:
      #- dockernet
    build:
      context: .
      dockerfile: Com.BudgetMetal.App/Dockerfile
    ports:
      - "9910:80"

networks:
    dockernet:
        external: true