version: '2'

services:
  budgetmetal_admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    image: budgetmetaladmin
    #network_mode: host
    networks:
      - dockernet
    build:
      context: .
      dockerfile: BudgetMetal_Admin/Dockerfile
    ports:
      - "9908:80"

  com.budgetmetal.services.galleryapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    image: combudgetmetalservicesgalleryapi
    #network_mode: host
    networks:
      - dockernet
    build:
      context: .
      dockerfile: Com.BudgetMetal.Services.GalleryAPI/Dockerfile
    ports:
      - "9909:80"

  com.budgetmetal.app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    image: combudgetmetalapp
    #network_mode: host
    networks:
      - dockernet
    build:
      context: .
      dockerfile: Com.BudgetMetal.App/Dockerfile
    ports:
      - "9910:80"

networks:
    dockernet:
        external: true