version: '2'

services:
  budgetmetal_admin:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Production
    image: budgetmetaladmin
    build:
      context: .
      dockerfile: BudgetMetal_Admin/Dockerfile

  com.budgetmetal.services.galleryapi:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Production
    image: combudgetmetalservicesgalleryapi
    build:
      context: .
      dockerfile: Com.BudgetMetal.Services.GalleryAPI/Dockerfile

  com.budgetmetal.app:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Production
    image: combudgetmetalapp
    build:
      context: .
      dockerfile: Com.BudgetMetal.App/Dockerfile