version: '2'

services:
  budgetmetal_admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: budgetmetaladmin
    build:
      context: .
      dockerfile: BudgetMetal_Admin/Dockerfile

  com.budgetmetal.services.gallery:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: combudgetmetalservicesgallery
    build:
      context: .
      dockerfile: Com.BudgetMetal.Services.Gallery/Dockerfile